# Generated by Django 3.2.5 on 2021-07-13 14:52

from django.db import migrations
import game_engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0002_match_usercode_userperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='players',
            field=game_engine.models.MatchPlayersField(default='{}'),
            preserve_default=False,
        ),
    ]
