# Generated by Django 3.2.5 on 2021-07-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0003_match_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='over',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
