# Generated by Django 3.2.5 on 2021-07-16 07:35

from django.db import migrations, models
import game_engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0004_auto_20210713_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='source_code',
            field=models.FileField(upload_to=game_engine.models.get_filename),
        ),
    ]
