# Generated by Django 3.2.5 on 2021-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0007_remove_user_github_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github_username',
            field=models.CharField(default='ILW8', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
