# Generated by Django 3.2.5 on 2021-07-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0008_user_github_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='usercode',
            name='has_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercode',
            name='is_latest',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='commit_time',
            field=models.DateTimeField(unique=True),
        ),
    ]
