# Generated by Django 3.2.5 on 2021-07-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0009_auto_20210717_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='is_in_game',
            field=models.BooleanField(default=False),
        ),
    ]
