# Generated by Django 3.2.5 on 2021-07-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0010_usercode_is_in_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='allocated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
