# Generated by Django 3.2.5 on 2021-07-18 21:23

from django.db import migrations, models
import game_engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0011_alter_match_allocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', game_engine.models.MatchPlayersField()),
                ('winners', game_engine.models.MatchPlayersField()),
                ('time_started', models.DateTimeField()),
                ('time_finished', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Match results',
            },
        ),
        migrations.AlterField(
            model_name='userperformance',
            name='mmr',
            field=models.DecimalField(decimal_places=4, default=2500.0, max_digits=8),
        ),
    ]
