# Generated by Django 3.2.5 on 2021-07-19 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0012_auto_20210718_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='time_finished',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
