# Generated by Django 3.2.5 on 2021-07-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0013_alter_matchresult_time_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperformance',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userperformance',
            name='mmr',
            field=models.DecimalField(decimal_places=2, default=2500.0, max_digits=8),
        ),
    ]
