# Generated by Django 3.2.5 on 2021-07-29 01:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0014_auto_20210720_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='match_events',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
