# Generated by Django 3.2.5 on 2021-07-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0015_matchresult_match_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperformance',
            name='confidence',
            field=models.DecimalField(decimal_places=7, default=8.33333, max_digits=12),
        ),
        migrations.AlterField(
            model_name='userperformance',
            name='mmr',
            field=models.DecimalField(decimal_places=6, default=25.0, max_digits=12),
        ),
    ]
