# Generated by Django 3.2.5 on 2021-08-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0016_auto_20210729_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='userperformance',
            name='league',
            field=models.IntegerField(default=0),
        ),
    ]
