# Generated by Django 3.2.5 on 2021-08-25 23:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0017_userperformance_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='match_events',
            field=jsonfield.fields.JSONField(),
        ),
    ]
