# Generated by Django 3.2.7 on 2021-09-14 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0019_user_authentication_token_squashed_0022_alter_user_authentication_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercode',
            name='is_latest',
        ),
        migrations.AddField(
            model_name='usercode',
            name='branch',
            field=models.CharField(default='master', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercode',
            name='commit_sha',
            field=models.CharField(default='', max_length=41),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercode',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercode',
            name='to_clone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userperformance',
            name='code',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game_engine.usercode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercode',
            name='commit_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userperformance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_engine.user'),
        ),
    ]
