# Generated by Django 3.2.5 on 2021-09-30 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0021_auto_20210922_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game_engine.user')),
                ('hide_identity', models.BooleanField(default=True)),
                ('display_name', models.CharField(blank=True, max_length=48, null=True, unique=True)),
            ],
        ),
    ]
