# Generated by Django 3.2.5 on 2021-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0022_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='display_name',
            field=models.IntegerField(choices=[(0, 'GitHub Username'), (1, 'Student ID'), (2, 'First and last names')], default=1),
        ),
    ]
