# Generated by Django 3.2.5 on 2021-07-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0008_user_github_username'),
        ('code_manager', '0002_alter_repository_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_engine.user'),
        ),
        migrations.DeleteModel(
            name='GithubUser',
        ),
    ]
